version: '3.9'
services:

  stepik-demo:
    image: stepik/demo
    ports:
      - "7070:7070"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    
      

